---
name: php
"on": pull_request
permissions:
  contents: read
  packages: read
jobs:
  mcvs-php-action:
    strategy:
      matrix:
        args:
          - testing-type: composer-validate
          - testing-type: security-composer-packages
          - testing-type: security-grype
    runs-on: ubuntu-24.04
    env:
      TASK_X_REMOTE_TASKFILES: 1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./
        with:
          task-install: yes
          testing-type: ${{ matrix.args.testing-type }}
          token: ${{ secrets.GITHUB_TOKEN }}
